#!/bin/bash

echo -e "Sisesta kasutaja vanus: "
read vanus

if [ $vanus -gt 0 -a $vanus -lt 11 ]; then
	echo "Oled laps."
elif [ $vanus -ge 11 -a $vanus -lt 18 ]; then
	echo "Oled nooruk."
elif [ $vanus -ge 18 -a $vanus -lt 63 ]; then
	echo "Oled täiskasvanu."
elif test $vanus -ge 63 -a $vanus -le 120; then
	echo "Oled seenior."
else
	echo "Vigane sisend, nii vana ei saa olla!"
fi
