#!/bin/bash

echo -n "Sisesta suvaline täisarv: "
read arv

#jagab jäägi 2ga
jaak=$(($arv % 2))

#tingimus, kas jääk on paaris või paaritu
if test $jaak -eq 0
then
	echo $arv" on paaris"
else
	echo $arv" on paaritu"
fi

