#!/bin/bash

osch=0
echo "1. Unix (Sun 0s)"
echo "2. Linux (Red Hat)"

echo -n "Select your OS choice [1 or 2]? "
read osch 

if [ $osch -eq 1 ]; then
	echo "You pick up Unix (Sun 0s)"
else
	if [ $osch -eq 2 ]; then
	echo "You pick up Linux (Red Hat)"
	else
	echo "What you don't like Unix/Linux OS."
	fi
fi

