#!/bin/bash

#Sisestatakse suvaline täisarv, nende numbrid iidetakse kokku
echo -n "Sisesta suvaline täisarv: "
read arv

summa=0
#Kui arv ei võrdu 0ga
while [ $arv -ne 0 ]
do
	#Jäägi leidmine ja 10-ga jagamine
	jaak=$(($arv % 10))
	#Lisatakse summasse
	summa=$(($summa + $jaak))
	#Väljastab ülejäänud arvud
	arv=$(($arv / 10))
done

echo "Arvu summa on $summa."


