#!/bin/bash

echo -n "Sisesta suvaline täisarv: "
read arv

if [ $arv -eq 0 -o $arv -eq 1 ]; then
	echo "Sisestatud arv ei ole algarv."
else
	#jagab 2ga seni kuni jääk on 0
	jagaja=2
	jaak=$(($arv % $jagaja))
	while [ $jaak -ne 0 ]
	do
		#liidab jagajale 1 juurde
		jagaja=$(($jagaja + 1))
		jaak=$(($arv % $jagaja))
	done
	#kontrollib, kas jagaja on võrdne arvuga
	if [ $arv -eq $jagaja ]; then
		echo "$arv on algarv."
	else
		echo "$arv ei ole algarv."
	fi
fi
